wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
architecture:
  desc: null
  value: retinanet_resnet50_fpn
dataset:
  desc: null
  value: coco
epochs:
  desc: null
  value: 25
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683045918.82449
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.0
      8:
      - 1
      - 3
      - 5
